In [113]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.datasets import load_boston
from sklearn.metrics import mean_squared_error, f1_score, accuracy_score, roc_curve, roc_auc_score
from sklearn.model_selection import train_test_split

from matplotlib import pyplot as plt

## 1. Линейная регрессия. Реализация

In [114]:
data = load_boston()
data['data'].shape

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets inclu

(506, 13)

In [115]:
type(data['data'])

numpy.ndarray

In [116]:
print(data['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

### 1.1. Реализация линейной регрессии с использованием матричных операций

Линейная регрессия выражается следующей зависимостью:
$$y=X\theta+\epsilon,$$
где $X$ — матрица объекты-признаки, $y$ — вектор целевых значений, соответствующих $X$, $\theta$ — параметр линейной регрессии, $\epsilon$ — некоторый шум.

Из данного следует выражение для $\theta$ как:
$$X^Ty=X^TX\theta \rightarrow \theta=(X^TX)^{-1}X^Ty$$

Реализуем выражение для $\theta$ с помощью операций линейной алгебры библиотеки Numpy:

In [117]:
# ЗАДАЧА Реализовать функцию, осуществляющую матричные операции для получения theta
# def linreg_linear(X, y):
    
#     return theta

In [118]:
# Подготовить данные

X, y = data['data'], data['target']

# Обучите регрессию без дополнительного столбца единиц. Какой получился RMSE?
X0 = data['data']

X = np.hstack([np.ones(X.shape[0])[:, np.newaxis], X])

#Очистите данные от строк, где значение признака  меньше . Какой получился RMSE?
X1 = [st for st in X if st[12]<50]
y1 = pd.DataFrame(y)
X2 = pd.DataFrame(X)
X2 = X2[X2[12]<50]


# Нормализуйте признаки и обучите линейную регрессию матричным методом. Какой получился RMSE?
X3 = pd.DataFrame(X)

In [119]:
type(X3)

pandas.core.frame.DataFrame

In [120]:
X3

0        1     2      3    4      5      6     7       8    9      10  \
0    1.0  0.00632  18.0   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    1.0  0.02731   0.0   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    1.0  0.02729   0.0   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    1.0  0.03237   0.0   2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    1.0  0.06905   0.0   2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..   ...      ...   ...    ...  ...    ...    ...   ...     ...  ...    ...   
501  1.0  0.06263   0.0  11.93  0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  1.0  0.04527   0.0  11.93  0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  1.0  0.06076   0.0  11.93  0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  1.0  0.10959   0.0  11.93  0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  1.0  0.04741   0.0  11.93  0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

       11      12    13  
0    15.3  396.90  4.98  
1    17.8  396.90  9.14  
2    17.8  392.83  4.03  
3    18.7  394.63  2.94  
4    18.7  396.90  5.33  
..    ...     ...   ...  
501  21.0  391.99  9.67  
502  21.0  396.90  9.08  
503  21.0  396.90  5.64  
504  21.0  393.45  6.48  
505  21.0  396.90  7.88  

[506 rows x 14 columns]

In [121]:
X2[14]=y1

In [122]:
y2=X2[14]

In [123]:
X2 = X2.drop(14, 1)

/var/folders/_q/03tkk3nx5xq63qd_bldrts5h0000gn/T/ipykernel_3296/1480947318.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X2 = X2.drop(14, 1)


In [124]:
X2

0         1    2     3    4      5      6      7       8     9      10  \
410  1.0  51.13580  0.0  18.1  0.0  0.597  5.757  100.0  1.4130  24.0  666.0   
411  1.0  14.05070  0.0  18.1  0.0  0.597  6.657  100.0  1.5275  24.0  666.0   
412  1.0  18.81100  0.0  18.1  0.0  0.597  4.628  100.0  1.5539  24.0  666.0   
415  1.0  18.08460  0.0  18.1  0.0  0.679  6.434  100.0  1.8347  24.0  666.0   
416  1.0  10.83420  0.0  18.1  0.0  0.679  6.782   90.8  1.8195  24.0  666.0   
418  1.0  73.53410  0.0  18.1  0.0  0.679  5.957  100.0  1.8026  24.0  666.0   
419  1.0  11.81230  0.0  18.1  0.0  0.718  6.824   76.5  1.7940  24.0  666.0   
423  1.0   7.05042  0.0  18.1  0.0  0.614  6.103   85.1  2.0218  24.0  666.0   
424  1.0   8.79212  0.0  18.1  0.0  0.584  5.565   70.6  2.0635  24.0  666.0   
425  1.0  15.86030  0.0  18.1  0.0  0.679  5.896   95.4  1.9096  24.0  666.0   
426  1.0  12.24720  0.0  18.1  0.0  0.584  5.837   59.7  1.9976  24.0  666.0   
427  1.0  37.66190  0.0  18.1  0.0  0.679  6.202   78.7  1.8629  24.0  666.0   
436  1.0  14.42080  0.0  18.1  0.0  0.740  6.461   93.3  2.0026  24.0  666.0   
437  1.0  15.17720  0.0  18.1  0.0  0.740  6.152  100.0  1.9142  24.0  666.0   
445  1.0  10.67180  0.0  18.1  0.0  0.740  6.459   94.8  1.9879  24.0  666.0   
450  1.0   6.71772  0.0  18.1  0.0  0.713  6.749   92.6  2.3236  24.0  666.0   
454  1.0   9.51363  0.0  18.1  0.0  0.713  6.728   94.1  2.4961  24.0  666.0   
456  1.0   4.66883  0.0  18.1  0.0  0.713  5.976   87.9  2.5806  24.0  666.0   
457  1.0   8.20058  0.0  18.1  0.0  0.713  5.936   80.3  2.7792  24.0  666.0   
466  1.0   3.77498  0.0  18.1  0.0  0.655  5.952   84.7  2.8715  24.0  666.0   

       11     12     13  
410  20.2   2.60  10.11  
411  20.2  35.05  21.22  
412  20.2  28.79  34.37  
415  20.2  27.25  29.05  
416  20.2  21.57  25.79  
418  20.2  16.45  20.62  
419  20.2  48.45  22.74  
423  20.2   2.52  23.29  
424  20.2   3.65  17.16  
425  20.2   7.68  24.39  
426  20.2  24.65  15.69  
427  20.2  18.82  14.52  
436  20.2  27.49  18.05  
437  20.2   9.32  26.45  
445  20.2  43.06  23.98  
450  20.2   0.32  17.44  
454  20.2   6.68  18.71  
456  20.2  10.48  19.01  
457  20.2   3.50  16.94  
466  20.2  22.01  17.15

In [125]:
# X2 = preprocessing.MinMaxScaler().fit_transform(X2)
# X2 = preprocessing.MinMaxScaler().transform(X2)

In [126]:
def normalization_df(X):
    result = X.copy()
    for column_name in X.columns:
        max_value = X[column_name].max()
        min_value = X[column_name].min()
        std_value = X[column_name].mean()
        if max_value == min_value:
            result[column_name] = 1
        else: 
            result[column_name] = (X[column_name] - min_value) / (max_value - min_value)
    return result

In [127]:
X_norm = normalization_df(X3)

In [128]:
X_norm

0         1     2         3    4         5         6         7   \
0     1  0.000000  0.18  0.067815  0.0  0.314815  0.577505  0.641607   
1     1  0.000236  0.00  0.242302  0.0  0.172840  0.547998  0.782698   
2     1  0.000236  0.00  0.242302  0.0  0.172840  0.694386  0.599382   
3     1  0.000293  0.00  0.063050  0.0  0.150206  0.658555  0.441813   
4     1  0.000705  0.00  0.063050  0.0  0.150206  0.687105  0.528321   
..   ..       ...   ...       ...  ...       ...       ...       ...   
501   1  0.000633  0.00  0.420455  0.0  0.386831  0.580954  0.681771   
502   1  0.000438  0.00  0.420455  0.0  0.386831  0.490324  0.760041   
503   1  0.000612  0.00  0.420455  0.0  0.386831  0.654340  0.907312   
504   1  0.001161  0.00  0.420455  0.0  0.386831  0.619467  0.889804   
505   1  0.000462  0.00  0.420455  0.0  0.386831  0.473079  0.802266   

           8         9         10        11        12        13  
0    0.269203  0.000000  0.208015  0.287234  1.000000  0.089680  
1    0.348962  0.043478  0.104962  0.553191  1.000000  0.204470  
2    0.348962  0.043478  0.104962  0.553191  0.989737  0.063466  
3    0.448545  0.086957  0.066794  0.648936  0.994276  0.033389  
4    0.448545  0.086957  0.066794  0.648936  1.000000  0.099338  
..        ...       ...       ...       ...       ...       ...  
501  0.122671  0.000000  0.164122  0.893617  0.987619  0.219095  
502  0.105293  0.000000  0.164122  0.893617  1.000000  0.202815  
503  0.094381  0.000000  0.164122  0.893617  1.000000  0.107892  
504  0.114514  0.000000  0.164122  0.893617  0.991301  0.131071  
505  0.125072  0.000000  0.164122  0.893617  1.000000  0.169702  

[506 rows x 14 columns]

In [129]:
X.shape

(506, 14)

In [130]:
y2.shape

(20,)

In [131]:
type(X2)

pandas.core.frame.DataFrame

In [132]:
type(X_norm)

pandas.core.frame.DataFrame

In [133]:
type(y2)

pandas.core.series.Series

In [134]:
y.shape

(506,)

In [135]:
len(X) 

506

In [136]:
len(X1) 

20

In [137]:
len(X2) 

20

In [138]:
X2 = X2.to_numpy()

In [139]:
X_norm = X_norm.to_numpy()

In [140]:
y2 = y2.to_numpy()

In [141]:
X2.shape

(20, 14)

In [142]:
# X1.shape

In [143]:
y2.shape

(20,)

In [144]:
type(X1)

list

In [145]:
type(X0)

numpy.ndarray

In [146]:
type(X2)

numpy.ndarray

In [147]:
type(y)

numpy.ndarray

In [148]:
type(y2)

numpy.ndarray

In [149]:
def linreg_linear(X, y):
    matr1 = np.dot(X.T, X)
    matr2 = np.linalg.inv(matr1)
    matr = np.dot(matr2, X.T)
    theta = np.dot(matr, y)
    return theta
    

In [150]:
# Вычислить параметр theta
theta = linreg_linear(X, y)
theta0 = linreg_linear(X0, y)


In [151]:
theta

array([ 3.64594884e+01, -1.08011358e-01,  4.64204584e-02,  2.05586264e-02,
        2.68673382e+00, -1.77666112e+01,  3.80986521e+00,  6.92224640e-04,
       -1.47556685e+00,  3.06049479e-01, -1.23345939e-02, -9.52747232e-01,
        9.31168327e-03, -5.24758378e-01])

In [152]:
np.linalg.norm(theta) 

40.867455573954125

In [153]:
theta2 = linreg_linear(X2, y2)

LinAlgError: Singular matrix

In [159]:
theta_norm = linreg_linear(X_norm, y)

In [160]:
theta

array([ 3.64594884e+01, -1.08011358e-01,  4.64204584e-02,  2.05586264e-02,
        2.68673382e+00, -1.77666112e+01,  3.80986521e+00,  6.92224640e-04,
       -1.47556685e+00,  3.06049479e-01, -1.23345939e-02, -9.52747232e-01,
        9.31168327e-03, -5.24758378e-01])

In [155]:
theta.shape

(14,)

In [156]:
theta_norm.shape

(14,)

In [161]:
np.linalg.norm(theta) 

40.867455573954125

In [162]:
# Сделать предсказания для тренировочной выборки
y_pred = np.dot(X, theta)
y0_pred = np.dot(X0, theta0)
y1_pred = np.dot(X1, theta1)
y2_pred = np.dot(X2, theta2)
y_norm_pred = np.dot(X_norm, theta_norm)
y_pred.shape

NameError: name 'theta1' is not defined

In [163]:
y_pred.shape

(506,)

In [164]:
y.shape

(506,)

In [165]:
def print_regression_metrics(y_true, y_pred):
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    print(f'MSE = {mse:.2f}, RMSE = {rmse:.3f}')

In [166]:
# Посчитать значение ошибок MSE и RMSE для тренировочных данных
print_regression_metrics(y, y_pred)
# Обучите регрессию без дополнительного столбца единиц. Какой получился RMSE?
print_regression_metrics(y, y0_pred)
print_regression_metrics(y2, y2_pred)
print_regression_metrics(y, y_norm_pred)


MSE = 21.89, RMSE = 4.679
MSE = 24.17, RMSE = 4.916


NameError: name 'y2_pred' is not defined

In [ ]:
X.max()

In [ ]:
xt=X.T
xt.shape
[np.std(xt[i]) for i in range(14)]

In [ ]:
def max_deviation(x):
    xt=x.T
    

In [ ]:
plt.hist(y);

In [ ]:
plt.hist(y_pred)

In [167]:
# Разбить выборку на train/valid, вычислить theta,
# сделать предсказания и посчитать ошибки MSE и RMSE

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2)
theta = linreg_linear(X_train, y_train)
y_pred = X_valid.dot(theta)
y_train_pred = X_train.dot(theta)

In [168]:
print_regression_metrics(y_valid, y_pred)
print_regression_metrics(y_train, y_train_pred)

MSE = 24.36, RMSE = 4.935
MSE = 21.73, RMSE = 4.661


In [169]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X,y)
y_pred = lr.predict(X)
print_regression_metrics(y, y_pred)

MSE = 21.89, RMSE = 4.679


In [170]:

lr0 = LinearRegression()
lr0.fit(X0,y)
y0_pred = lr0.predict(X0)
print_regression_metrics(y, y0_pred)

MSE = 21.89, RMSE = 4.679


### 1.2. Реализация линейной регрессии с использованием методов оптимизации

Для реализации линейной регрессии с помощью методов оптимизации будем использовать функцию ошибки **среднего квадратичного** ([Mean Squared Error](https://en.wikipedia.org/wiki/Mean_squared_error)), которая является выпуклой функцией в n-мерном пространстве $\mathbb{R}^n$ и в общем виде выглядит следующим образом:
$$MSE = \frac{1}{n} * \sum_{i=1}^{n}{(y_i - a(x_i))^2}.$$
Здесь $x_i$ — вектор-признак $i$-го объекта обучающей выборки, $y_i$ — истинное значение для $i$-го объекта, $a(x)$ — алгоритм, предсказывающий для данного объекта $x$ целевое значение, $n$ — кол-во объектов в выборке.

В случае линейной регрессии $MSE$ представляется как:
$$MSE(X, y, \theta) = \frac{1}{2n} * \sum_{i=1}^{n}{(y_i - \theta^Tx_i)^2} = \frac{1}{2n} \lVert{y - X\theta}\rVert_{2}^{2}=\frac{1}{2n} (y - X\theta)^T(y - X\theta),$$
где $\theta$ — параметр модели линейной регрессии, $X$ — матрица объекты-признаки, $y$ - вектор истинных значений, соответствующих $X$.

Возьмем первый вариант представления функции ошибки и посчитаем ее градиент по параметру $\theta$, предварительно переименовав $MSE$ в $L$:
$$L=\frac{1}{2n} * \sum_{i=1}^{n}{(y_i - \theta^Tx_i)^2}$$
$$\nabla L = \frac{1}{n}\sum_{i=1}^{n}{(\theta^Tx_i - y_i) \cdot x_i} = \frac{1}{n}X^T(X\theta - y)$$

Исходя из полученного выражения градиента, реализуем алгоритм градиентного спуска:

In [171]:
# Реализовать функцию вычисления градиента функции MSE

def calc_mse_gradient(X, y, theta):
    n = X.shape[0]
    grad = 1. / n * X.transpose().dot(X.dot(theta) - y)
    
    return grad

In [172]:
# Реализовать функцию, осуществляющую градиентный шаг
# (функция должна содержать параметр величины шага alpha - learning rate)

def gradient_step(theta, theta_grad, alpha):
    return theta - alpha * theta_grad

In [173]:
# Реализовать функцию цикла градиентного спуска с доп. параметрами
# начального вектора theta и числа итераций

def optimize(X, y, grad_func, start_theta, alpha, n_iters):
    theta = start_theta.copy()
    
    for i in range(n_iters):
        theta_grad = grad_func(X, y, theta)
        theta = gradient_step(theta, theta_grad, alpha)
    
    return theta


In [174]:
# Разбить таблицу данных на матрицы X и y
X, y = data['data'], data['target']

# Добавить фиктивный столбец единиц (bias линейной модели)
X = np.hstack([np.ones(X.shape[0])[:, np.newaxis], X])
m = X.shape[1]

In [175]:
# Оптимизировать параметр линейной регрессии theta на всех данных
theta = optimize(X, y, calc_mse_gradient, np.ones(m), 0.001, 100)

In [176]:
theta

array([7.41647399e+246, 3.32349992e+247, 7.39564172e+247, 8.96295209e+247,
       5.07578059e+245, 4.22030567e+246, 4.63094053e+247, 5.29083888e+248,
       2.65643383e+247, 8.19991211e+247, 3.27135991e+249, 1.38363846e+248,
       2.64323053e+249, 9.88835598e+247])

In [178]:
np.linalg.norm(theta) 

inf

In [177]:
# Проверить максимальные значения по каждому признаку в данных
X.max(axis=0)

array([  1.    ,  88.9762, 100.    ,  27.74  ,   1.    ,   0.871 ,
         8.78  , 100.    ,  12.1265,  24.    , 711.    ,  22.    ,
       396.9   ,  37.97  ])

In [179]:
print(data['feature_names'][np.argmax(X.std(axis=0)) + 1])
print(np.max(X.std(axis=0)))

B
168.3704950393814


In [180]:
# Нормализовать даннные с помощью стандартной нормализации
X, y = data['data'], data['target']
X = (X - X.mean(axis=0)) / X.std(axis=0)

In [ ]:
# Добавить фиктивный столбец единиц (bias линейной модели)
X = np.hstack([np.ones(X.shape[0])[:, np.newaxis], X])
X.max(axis=0)

In [ ]:
# Оптимизировать theta на новых данных
theta = optimize(X, y, calc_mse_gradient, np.ones(m), 0.01, 5000)

In [ ]:
theta

In [ ]:
# Сделать предсказания при полученных параметрах
y_pred = X.dot(theta)

In [ ]:
# Посчитать значение ошибок MSE и RMSE для тренировочных данных
print_regression_metrics(y, y_pred)

In [ ]:
# Разбить выборку на train/valid, оптимизировать theta,
# сделать предсказания и посчитать ошибки MSE и RMSE

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2)
theta = optimize(X_train, y_train, calc_mse_gradient, np.ones(m), 0.01, 5000)
y_pred = X_valid.dot(theta)

print_regression_metrics(y_valid, y_pred)